### ISSUE TITLE
Remove transitions from global selector

### ISSUE THREAD

**Issue by cchaos** [USEPA/OneEPA-Standalone-App-Template#13]
https://github.com/USEPA/OneEPA-Standalone-App-Template/blob/8c567753e1665eef2f406858d3b8a3ba090722de/css/core/style.css#L376-L382

Universally adding transitions to all elements contained in such generic elements can and does cause a lot of unneeded overrides to remove these transitions. Even though they target a select few properties, these transitions can cause unintended and ill-timed distractions.

**Comment by cherrypj** [comment]
Should these transitions target any element? Or should they be removed entirely?

**Comment by cchaos** [comment]
The only elements that I see that actually utilize the transitions are:

* `.menu-link`s' background-color
* `.epa-search-button`'s background-color and border-color

You could think about just applying the `.25s linear` transition to these specific elements and their specific attributes that change.

**Comment by cchaos** [comment]
Oh sorry, I forgot to check the mobile menu as well. These elements also use the transition

* `.menu-button`'s background-color
* `.mobile-links a`'s background-color

**Comment by cherrypj** [comment]
#14 

Also removes the vendor-specific prefixes.
