### ISSUE TITLE
Make npm available

### ISSUE THREAD

**Issue by shawnadrockleonard** [USEPA/OneEPA-Standalone-App-Template#21]
Can you make this available in NPM or another popular repository so the theme/structure can be included in downstream applications?   If this is already possible, do you have a guide for implementation?

**Comment by samhebert1** [comment]
I would second that for sure!

**Comment by cherrypj** [comment]
At this time, no. We will be moving away from this template in a few months.

**Comment by samhebert1** [comment]
Nice to know, thanks.
