### ISSUE TITLE
"href" in header if on cloud.gov

### ISSUE THREAD

**Issue by dwahman** [USEPA/OneEPA-Standalone-App-Template#22]
There are relative references with "href" in the header (5 or 6).  This become an issue when not hosted on an epa.gov site as is the case if R shiny applications are hosted on cloud.gov.  This causes the links to not work.  Please consider changing these to full addresses.

**Comment by cherrypj** [comment]
Hi. I'm not sure what you mean? Every link in the template is an absolute link.

**Comment by dwahman** [comment]
Here is a portion of the relevant code from the ui.R file.  I have highlighted (in green) some instances where issues are caused if not housed on epa.gov.  I don’t know if this is all of them.

# ui.R


fluidPage(


tags$head(tags$link(rel = "stylesheet",


type = "text/css", href = "style.css")),


# Header


HTML("<header class='masthead clearfix' role='banner'>


<img alt='' class='site-logo' src='https://www.epa.gov/sites/all/themes/epa/logo.png'>


<div class='site-name-and-slogan'>


<h1 class='site-name'><a href='/' rel='home' title='Go to the home page'><span>US EPA</span></a></h1>


<div class='site-slogan'>


United States Environmental Protection Agency


</div>


</div>


<div class='region-header'>


<div class='block-epa-core-gsa-epa-search' id='block-epa-core-gsa-epa-search'>"),



# Search Form


#$form(action='https://search.epa.gov/epasearch/epasearch', class='epa-search', method='get',


# tags$label(class='element-hidden'),


# tags$input(autocomplete='off', class='form-text ui-autocomplete-input', id='search-box', name='querytext', placeholder='Search EPA.gov', value=''),


# tags$span( class='ui-helper-hidden-accessible', role='status'),


# tags$button(class='epa-search-button', id='search-button', title='Search', type='submit'),


# tags$input(name='areaname', type='hidden', value=''),


# tags$input(name='areacontacts', type='hidden', value=''),


# tags$input(name='areasearchurl', type='hidden', value=''),


# tags$input(name='typeofsearch', type='hidden', value='epa'),


# tags$input(name='result_template', type='hidden', value='2col.ftl')


#),



HTML("</div>


</div>


</header>


<nav class='nav main-nav clearfix' role='navigation'>


<div class='nav__inner'>


<h2 class='element-invisible'>Main menu</h2>


<ul class='menu' role='menu'>


<li class='expanded active-trail menu-item' role='presentation'>


<a class='active-trail menu-link' href='/environmental-topics' role='menuitem' title='View links to the most popular pages for each of EPA?s top environmental topics.'>Environmental Topics</a></li>


<li class='menu-item' role='presentation'>


<a class='menu-link' href='/laws-regulations' role='menuitem' title='View links to regulatory information by topic and sector, and to top pages about environmental laws, regulations, policies, compliance, and enforcement.'>Laws &amp; Regulations</a></li>


<li class='expanded menu-item' role='presentation'>


<a class='menu-link' href='/aboutepa' role='menuitem' title='Learn more about our mission, organization, and locations.'>About EPA</a></li>


</ul>


</div>


</nav>


<div class='mobile-nav' id='mobile-nav'>


<div class='mobile-bar clearfix'>


<label class='menu-button' for='mobile-nav-toggle'>Menu</label>


</div><input checked id='mobile-nav-toggle' type='checkbox'>


<div class='mobile-links element-hidden' id='mobile-links' style='height:2404px;'>


<ul class='mobile-menu'>


<li class='expanded menu-item'><a class='menu-link' href='https://www.epa.gov/environmental-topics' tabindex='-1' title='View links to the most popular pages for each of EPA?s top environmental topics.'>Environmental Topics</a></li>


<li class='menu-item'><a class='menu-link' href='https://www.epa.gov/laws-regulations' tabindex='-1' title='View links to regulatory information by topic and sector, and to top pages about environmental laws, regulations, policies, compliance, and enforcement.'>Laws &amp; Regulations</a></li>


<li class='expanded menu-item'><a class='menu-link' href='https://www.epa.gov/aboutepa' tabindex='-1' title='Learn more about our mission, organization, and locations.'>About EPA</a></li>


</ul>


</div>


</div>


<section class='main-content clearfix' id='main-content' lang='en' role='main' tabindex='-1'>


<div class='region-preface clearfix'>


<div class='block-views-revision-hublinks-block' id='block-views-revision-hublinks-block'>


<div class='view view-revision-hublinks view-id-revision_hublinks'>


<span class='related-info'><strong>Related Topics:</strong></span>


<ul class='menu pipeline'>


<li class='menu-item'><a href='/environmental-topics'>Environmental Topics</a></li>


</ul>


</div>


</div>



*****************************************
David G. Wahman, Ph.D., P.E.
Research Environmental Engineer
Drinking Water Treatment and Distribution Branch
Water Systems Division
National Risk Management Research Laboratory
U.S. Environmental Protection Agency
26 West Martin Luther King Drive
Cincinnati, Ohio 45268
Phone: (513) 569-7733
Fax: (513) 487-2543
wahman.david@epa.gov
*****************************************

**Comment by cherrypj** [comment]
Fixed.
