### ISSUE TITLE
Colon where semi-colon should be.

### ISSUE THREAD

**Issue by chorn99** [USEPA/OneEPA-Standalone-App-Template#4]
https://github.com/USEPA/OneEPA-Standalone-App-Template/blob/6f12aee8153348bf4ada8abcb557b9e56fcccd9f/css/core/style.css#L374

At the end of the declaration there is a colon instead of a semi-colon which causes a compilation error when using a pre-processor.

**Comment by cherrypj** [comment]
Thanks!
