### ISSUE TITLE
Wrong breakpoint for search form border & button

### ISSUE THREAD

**Issue by chorn99** [USEPA/OneEPA-Standalone-App-Template#5]
https://github.com/USEPA/OneEPA-Standalone-App-Template/blob/6f12aee8153348bf4ada8abcb557b9e56fcccd9f/css/core/style.css#L527-L531

https://github.com/USEPA/OneEPA-Standalone-App-Template/blob/6f12aee8153348bf4ada8abcb557b9e56fcccd9f/css/core/style.css#L589-L593

These breakpoints should be `65em` instead of `61em` to match when the search form actually gets moved into the .main-nav:

https://github.com/USEPA/OneEPA-Standalone-App-Template/blob/6f12aee8153348bf4ada8abcb557b9e56fcccd9f/css/core/style.css#L487-L499

**Comment by cherrypj** [comment]
Thanks!
